export const CAUSE_OF_DEATH_SCENE = {
  type: 'Cause of Death',
  values: ['Suffocation', 'Severe Injury', 'Blood Loss', 'Illness', 'Poisoning', 'Accident']
}

export const LOCATION_SCENE = {
  type: 'Location of Crime',
  values: [
    'Pub', 'Bookstore', 'Restaurant', 'Hotel', 'Hospital', 'Construction Site',
    'Living Room', 'Bedroom', 'Storeroom', 'Bathroom', 'Kitchen', 'Balcony',
    'Playground', 'Classroom', 'Dormitory', 'Cafeteria', 'Elevator', 'Toilet',
    'Vacation Home', 'Park', 'Supermarket', 'School', 'Woods', 'Bank',
  ],
}

export const SCENES = [
  {
    type: 'Day of Crime',
    values: ['Weekday', 'Weekend', 'Spring', 'Summer', 'Autumn', 'Winter']
  }, {
    type: 'In Progress',
    values: ['Entertainment', 'Relaxation', 'Assemply', 'Trading', 'Visit', 'Dining']
  }, {
    type: 'Victim\'s Build',
    values: ['Overweight', 'Underweight', 'Tall', 'Short', 'Muscular', 'Average']
  }, {
    type: 'Victim\'s Expression',
    values: ['Peaceful', 'Struggling', 'Frightened', 'In Pain', 'Blank', 'Angry']
  }, {
    type: 'General Impression',
    values: ['Common', 'Creative', 'Fishy', 'Cruel', 'Horrible', 'Suspenseful']
  }, {
    type: 'Victim\'s Clothes',
    values: ['Neat', 'Average', 'Untidy', 'Shabby', 'Bizzare', 'Naked']
  }, {
    type: 'Duration of Crime',
    values: ['Instant', 'Brief', 'Gradual', 'Prolonged', 'Few Days', 'Unclear']
  }, {
    type: 'Hint on Corpse',
    values: ['Head', 'Chest', 'Leg', 'Hand', 'Partial', 'All over']
  }, {
    type: 'Victim\'s Identity',
    values: ['Child', 'Young Adult', 'Middle Aged', 'Senior', 'Male', 'Female']
  }, {
    type: 'Sudden Incident',
    values: ['Power Failure', 'Fire', 'Conflict', 'Loss of Valuables', 'Scream', 'Nothing']
  }, {
    type: 'Time of Death',
    values: ['Dawn', 'Morning', 'Noon', 'Afternoon', 'Evening', 'Night']
  }, {
    type: 'Weather',
    values: ['Sunny', 'Stormy', 'Dry', 'Humid', 'Cold', 'Hot']
  }, {
    type: 'Social Relationship',
    values: ['Relatives', 'Employer', 'Friends', 'Colleagues', 'Lovers', 'Strangers']
  }, {
    type: 'Evidence Left Behind',
    values: ['Natural', 'Artistic', 'Written', 'Synthetic', 'Personal', 'Unrelated']
  }, {
    type: 'State of the Scene',
    values: ['Bits and Pieces', 'Ashes', 'Water Stain', 'Cracked', 'Disorderly', 'Tidy']
  }, {
    type: 'Motive of Crime',
    values: ['Hatred', 'Power', 'Money', 'Love', 'Jealousy', 'Justice']
  }, {
    type: 'Murderer\'s Personality',
    values: ['Arrogant', 'Despicable', 'Furious', 'Greedy', 'Forceful', 'Perverted']
  }, {
    type: 'Trace at Scene',
    values: ['Fingerprint', 'Footprint', 'Bruise', 'Blood Stain', 'Bodily Fluid', 'Scar']
  }, {
    type: 'Corpse Condition',
    values: ['Still Warm', 'Stiff', 'Decayed', 'Incomplete', 'Intact', 'Twisted']
  }, {
    type: 'Victim\'s Occupation',
    values: ['Boss', 'Professional', 'Worker', 'Student', 'Unemployed', 'Retired']
  }, {
    type: 'Noticed by Bystander',
    values: ['Sudden Sound', 'Prolonged Sound', 'Small', 'Visual', 'Action', 'Nothing']
  },
]

export const MEANS = [
  'Alcohol',
  'Amoeba',
  'Arsenic',
  'Arson',
  'Axe',
  'Bamboo Tip',
  'Bat',
  'Belt',
  'Bite And Tear',
  'Blender',
  'Blood Release',
  'Box Cutter',
  'Brick',
  'Bury',
  'Candlestick',
  'Chainsaw',
  'Chemicals',
  'Cleaver',
  'Crutch',
  'Dagger',
  'Dirty Water',
  'Dismember',
  'Drill',
  'Drown',
  'Dumbbell',
  'E-Bike',
  'Electric Baton',
  'Electric Current',
  'Explosives',
  'Folding Chair',
  'Gunpowder',
  'Hammer',
  'Hook',
  'Ice Skates',
  'Illegal Drug',
  'Injection',
  'Kerosene',
  'Kick',
  'Knife And Fork',
  'Lighter',
  'Liquid Drug',
  'Locked Room',
  'Machete',
  'Machine',
  'Mad Dog',
  'Match',
  'Mercury',
  'Metal Chain',
  'Metal Wire',
  'Overdose',
  'Packing Tape',
  'Pesticide',
  'Pill',
  'Pillow',
  'Pistol',
  'Plague',
  'Plastic Bag',
  'Poisonous Gas',
  'Poisonous Needle',
  'Potted Plant',
  'Powder Drug',
  'Punch',
  'Push',
  'Radiation',
  'Razor Blade',
  'Rope',
  'Scarf',
  'Scissors',
  'Sculpture',
  'Smoke',
  'Sniper',
  'Starvation',
  'Steel Tube',
  'Stone',
  'Sulfuric Acid',
  'Surgery',
  'Throat Slit',
  'Towel',
  'Trophy',
  'Trowel',
  'Unarmed',
  'Venomous Scorpion',
  'Venomous Snake',
  'Video Game Console',
  'Virus',
  'Whip',
  'Wine',
  'Wire',
  'Work',
  'Wrench',
]
export const CLUES = [
  'Air Conditioning',
  'Ants',
  'Antique',
  'Apple',
  'Badge',
  'Bandage',
  'Banknote',
  'Bell',
  'Betting Chips',
  'Blood',
  'Bone',
  'Book',
  'Bracelet',
  'Bread',
  'Briefs',
  'Broom',
  'Bullet',
  'Button',
  'Cake',
  'Calender',
  'Candy',
  'Carton',
  'Cassette Tape',
  'Cat',
  'Certificate',
  'Chalk',
  'Cigar',
  'Cigarette Ash',
  'Cigarette Butt',
  'Cleaning Cloth',
  'Cockroach',
  'Coffee',
  'Coins',
  'Comics',
  'Computer',
  'Computer Disk',
  'Computer Mouse',
  'Confidential Letter',
  'Cosmetic Mask',
  'Cotton',
  'Cup',
  'Curtains',
  'Dentures',
  'Diamond',
  'Diary',
  'Dice',
  'Dictionary',
  'Dirt',
  'Documents',
  'Dog Fur',
  'Dust',
  'Earrings',
  'Eggs',
  'Electric Circuit',
  'Envelope',
  'Exam Paper',
  'Express Courier',
  'Fan',
  'Fax',
  'Fiber Optics',
  'Fingernails',
  'Flashlight',
  'Flip-Flop',
  'Flute',
  'Flyer',
  'Food Ingredients',
  'Gear',
  'Gift',
  'Gloves',
  'Glue',
  'Graffiti',
  'Hair',
  'Hairpin',
  'Handcuffs',
  'Hanger',
  'Hat',
  'Headset',
  'Helmet',
  'Herbal Medicine',
  'High Heel',
  'Hourglass',
  'Ice',
  'ID Card',
  'Ink',
  'Insect',
  'Internet Cable',
  'Invitation Card',
  'IOU Note',
  'Iron',
  'IV Bag',
  'Jacket',
  'Jewelry',
  'Juice',
  'Key',
  'Leaf',
  'Leather Bag',
  'Leather Shoe',
  'Lens',
  'Light Bulb',
  'Lipstick',
  'Lock',
  'Lottery Ticket',
  'Love Letter',
  'Luggage',
  'Lunch Box',
  'Magazine',
  'Mahjong Tiles',
  'Map',
  'Mark',
  'Mask',
  'Maze',
  'Menu',
  'Mirror',
  'Mobile Phone',
  'Model',
  'Mosquito',
  'Mosquito Coil',
  'Nail',
  'Name Card',
  'Necklace',
  'Needle And Thread',
  'Newspaper',
  'Note',
  'Notebook',
  'Numbers',
  'Office Supplies',
  'Oil Painting',
  'Oil Stain',
  'Paint',
  'Panties',
  'Peanut',
  'Perfume',
  'Photograph',
  'Plant',
  'Plastic',
  'Playing Cards',
  'Pocket Watch',
  'Postal Stamp',
  'Powder',
  'Prescription',
  'Puppet',
  'Push Pin',
  'Puzzle',
  'Raincoat',
  'Rat',
  'Receipt',
  'Red Wine',
  'Riddle',
  'Ring',
  'Rose',
  'Rubber Stamp',
  'Sack',
  'Safety Pin',
  'Sand',
  'Sawdust',
  'Seasoning',
  'Signature',
  'Skull',
  'Snacks',
  'Soap',
  'Sock',
  'Soft Drink',
  'Speaker',
  'Specimen',
  'Spider',
  'Spinning Top',
  'Sponge',
  'Spring',
  'Steamed Buns',
  'Stockings',
  'Stuffed Toy',
  'Suit',
  'Sunglasses',
  'Surgical Mask',
  'Surveillance Camera',
  'Switch',
  'Syringe',
  'Table Lamp',
  'Take-Out',
  'Tattoo',
  'Tea Leaves',
  'Telephone',
  'Test Tube',
  'Tie',
  'Timber',
  'Tissue',
  'Tool Box',
  'Toothpicks',
  'Toy',
  'Toy Blocks',
  'Tweezers',
  'Umbrella',
  'Uniform',
  'USB Flash Drive',
  'Vegetables',
  'Video Camera',
  'Violin',
  'Wallet',
  'Watch',
  'Wig',
]